In [1]:
import numpy as np
import pandas as pd

In [2]:
# ocupa 80% ou mais do tempo de um analista

In [3]:
# Tratando dados ausentes

In [7]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado']) # o valor nan é conhecido como valor sentinela
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [8]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [9]:
string_data[0] = None

In [10]:
string_data.isnull() # o valor None é conhecido também como valor nan

0     True
1    False
2     True
3    False
dtype: bool

In [12]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [14]:
string_data.dropna() # pega somente os valores que não são nan

1    artichoke
3      avocado
dtype: object

In [18]:
string_data.fillna('fill') # preenche os nan

0         fill
1    artichoke
2         fill
3      avocado
dtype: object

In [19]:
string_data.fillna('bfill') # preenche os nan

0        bfill
1    artichoke
2        bfill
3      avocado
dtype: object

In [20]:
string_data.notnull()

0    False
1     True
2    False
3     True
dtype: bool

In [21]:
# Filtrando dados ausentes

In [6]:
from numpy import nan as NA

In [23]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [24]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [26]:
data.dropna() # equivalente a função de baixo

0    1.0
2    3.5
4    7.0
dtype: float64

In [27]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1, NA, NA],
                    [NA, NA, NA], [NA, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
data.dropna() # se tiver apenas um valor NA ele já não pega mais

0    1    2
0  1.0  6.5  3.0

In [9]:
data.dropna(how='all') # apenas as colunas que contenham somente NAs

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data[4] = NA # quarta coluna vira tudo NA

In [15]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [16]:
data.dropna(how="all", axis=1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
df = pd.DataFrame(np.random.randn(7, 3))

In [18]:
df

0         1         2
0  1.234570  0.667491 -1.083025
1  1.779963 -0.136033  0.038459
2 -0.927562  0.880371  0.471582
3 -0.416527  1.479074 -0.499527
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [19]:
df.iloc[:4, 1] = NA
df

0         1         2
0  1.234570       NaN -1.083025
1  1.779963       NaN  0.038459
2 -0.927562       NaN  0.471582
3 -0.416527       NaN -0.499527
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [20]:
df.iloc[:2, 2] = NA
df

0         1         2
0  1.234570       NaN       NaN
1  1.779963       NaN       NaN
2 -0.927562       NaN  0.471582
3 -0.416527       NaN -0.499527
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [23]:
df.dropna(thresh=2) # removeu os ultimos

0         1         2
2 -0.927562       NaN  0.471582
3 -0.416527       NaN -0.499527
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [24]:
df

0         1         2
0  1.234570       NaN       NaN
1  1.779963       NaN       NaN
2 -0.927562       NaN  0.471582
3 -0.416527       NaN -0.499527
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [26]:
df.iloc[0, 0] = NA
df

0         1         2
0       NaN       NaN       NaN
1  1.779963       NaN       NaN
2 -0.927562       NaN  0.471582
3 -0.416527       NaN -0.499527
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [28]:
df.dropna(thresh=1) # remove 1 em todos os NaN cuidado com o axis default

0         1         2
1  1.779963       NaN       NaN
2 -0.927562       NaN  0.471582
3 -0.416527       NaN -0.499527
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [30]:
df.dropna() # pega só os puros, linha e coluna sem na

0         1         2
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [31]:
# Preenchendo dados ausentes

In [32]:
df.fillna(0)

0         1         2
0  0.000000  0.000000  0.000000
1  1.779963  0.000000  0.000000
2 -0.927562  0.000000  0.471582
3 -0.416527  0.000000 -0.499527
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [33]:
df.fillna({0: 0.5, 1: 0.5, 2: 0}) # o que quer fazer atráves das colunas

0         1         2
0  0.500000  0.500000  0.000000
1  1.779963  0.500000  0.000000
2 -0.927562  0.500000  0.471582
3 -0.416527  0.500000 -0.499527
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [37]:
_ = df.fillna(0, inplace=True) #  inplace True, ou seja os valores modificam permanente

In [38]:
df

0         1         2
0  0.000000  0.000000  0.000000
1  1.779963  0.000000  0.000000
2 -0.927562  0.000000  0.471582
3 -0.416527  0.000000 -0.499527
4 -1.960035 -0.250509 -0.809780
5  1.332815  0.341067  0.244641
6  1.029540  1.337191 -0.917586

In [39]:
df = pd.DataFrame(np.random.randn(6, 3))
df

0         1         2
0  0.743370  0.934751  1.297001
1 -1.206709 -0.801806  0.001480
2 -0.288961 -0.487732 -0.325912
3 -1.325775  1.238328  0.541716
4  0.391746  2.055831 -0.052300
5  1.548932 -0.134037  1.163274

In [41]:
df.iloc[2:, 1] = NA
df

0         1         2
0  0.743370  0.934751  1.297001
1 -1.206709 -0.801806  0.001480
2 -0.288961       NaN -0.325912
3 -1.325775       NaN  0.541716
4  0.391746       NaN -0.052300
5  1.548932       NaN  1.163274

In [42]:
df.iloc[4:, 2] = NA
df

0         1         2
0  0.743370  0.934751  1.297001
1 -1.206709 -0.801806  0.001480
2 -0.288961       NaN -0.325912
3 -1.325775       NaN  0.541716
4  0.391746       NaN       NaN
5  1.548932       NaN       NaN

In [45]:
df.fillna(method='ffill') # na coluna o ultimo valor acima de nan, copia ele

0         1         2
0  0.743370  0.934751  1.297001
1 -1.206709 -0.801806  0.001480
2 -0.288961 -0.801806 -0.325912
3 -1.325775 -0.801806  0.541716
4  0.391746 -0.801806  0.541716
5  1.548932 -0.801806  0.541716

In [47]:
df

0         1         2
0  0.743370  0.934751  1.297001
1 -1.206709 -0.801806  0.001480
2 -0.288961       NaN -0.325912
3 -1.325775       NaN  0.541716
4  0.391746       NaN       NaN
5  1.548932       NaN       NaN

In [48]:
df.fillna(method='ffill', limit=2) # os dois primeiros da coluna

0         1         2
0  0.743370  0.934751  1.297001
1 -1.206709 -0.801806  0.001480
2 -0.288961 -0.801806 -0.325912
3 -1.325775 -0.801806  0.541716
4  0.391746       NaN  0.541716
5  1.548932       NaN  0.541716

In [49]:
data = pd.Series([1., NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [50]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [51]:
# Transformação de dados

In [52]:
# removendo duplicatas

In [54]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                    'k2': [1, 1, 2, 3, 3, 4, 4]})

In [55]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [58]:
data.duplicated() # linha com valores iguais ambas

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [61]:
data.drop_duplicates() # remove linhas duplicadas

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [62]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [63]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [65]:
data['k1']

0    one
1    two
2    one
3    two
4    one
5    two
6    two
Name: k1, dtype: object

In [66]:
data['k1'].duplicated()

0    False
1    False
2     True
3     True
4     True
5     True
6     True
Name: k1, dtype: bool

In [68]:
data.drop_duplicates(['k1']) 

k1  k2  v1
0  one   1   0
1  two   1   1

In [71]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [74]:
data.drop_duplicates(['k1', 'k2'], keep='last') # devolverá a ultima

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [78]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                    'k2': [1, 1, 2, 3, 3, 4, 4]})

In [79]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [80]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [84]:
data.drop_duplicates() # linha 79

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [85]:
# Transformando dados usando uma função ou mapeamento

In [86]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                             'Pastrami', 'corned beef', 'Bacon',
                             'pastrami', 'honey ham', 'nova lox'],
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [96]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [97]:
lowercased = data['food'].str.lower()
lowercased # o Bacon virou bacon

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [100]:
lowercased.map(meat_to_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [103]:
data['animal'] = lowercased.map(meat_to_animal) 
# faz entender um e o outro ex bacon é pig, como que é o lowercased que está fazendo
# o map, ou seja o bacon do lowercased é igual o bacon do meat_to_animal que é um pig
# lowercased bacon = bacon do meat_to_animal é : pig, com isso reconhece sempre que aparecer um lowercased colocar um pig

In [104]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [105]:
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [102]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [109]:
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [110]:
data['food']

0          bacon
1    pulled pork
2          bacon
3       Pastrami
4    corned beef
5          Bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [118]:
data['food'].map(lambda x: meat_to_animal[x.lower()]) # é igual a do 117 porém mais dificil

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [119]:
meat_to_animal['bacon'] # entendeu ?

'pig'

In [120]:
lowercased.map(meat_to_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [2]:
# map é uma forma conveninete de fazer transformações em todos os elementos e executar outras operações relacionadas à limpeza
# de dado

In [3]:
# Substituindo valores

In [4]:
# fillna é um caso especial da substituição mais genérica de valores
# replace é mais simples e mais flexível
data = pd.Series([1., -999., 2., -999, -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [5]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [6]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [7]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [8]:
data.replace([-999, -1000], [np.nan, 0]) # valores combinados

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [9]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [10]:
# Renomeando os índices dos eixos

In [12]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                   index=['Ohio', 'Colorado', 'New York'],
                   columns=['one', 'two', 'three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [13]:
transform = lambda x: x[:4].upper()

In [16]:
data.index

Index(['Ohio', 'Colorado', 'New York'], dtype='object')

In [18]:
data.index.map(transform) # .map passa os dados da data para o transform

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [20]:
data.rename(index=str.title, columns=str.upper) # mais eficaz

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [21]:
data.rename(index={'OHIO': 'INDIANA'},
           columns={'three': 'peekaboo'})

one  two  peekaboo  four
Ohio        0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

In [24]:
data.rename(index={'Ohio': 'INDIANA'}, inplace=True)

In [25]:
data

one  two  three  four
INDIANA     0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [28]:
data.replace(0, np.nan)

one  two  three  four
INDIANA   NaN    1      2     3
Colorado  4.0    5      6     7
New York  8.0    9     10    11

In [29]:
data.replace([4, 8, 1], np.nan)

one  two  three  four
INDIANA   0.0  NaN    2.0   3.0
Colorado  NaN  5.0    6.0   7.0
New York  NaN  9.0   10.0  11.0

In [30]:
data.replace({5: 10, 6: 12})

one  two  three  four
INDIANA     0    1      2     3
Colorado    4   10     12     7
New York    8    9     10    11

In [32]:
data.rename(index=str.title, columns=str.title)

One  Two  Three  Four
Indiana     0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [38]:
data.rename(index={'Colorado': 'um'})

one  two  three  four
INDIANA     0    1      2     3
um          4    5      6     7
New York    8    9     10    11

In [39]:
# Discretização e compartimentalização (binning)

In [51]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
ages

[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [52]:
bins = [18, 25, 35, 60, 100] # compartimentos 18 a 25, 25 -35

In [54]:
cats = pd.cut(ages, bins) 
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [46]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [55]:
cats.categories # categorias

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [56]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [58]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [59]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [60]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [61]:
data = np.random.rand(20)
data

array([0.6882258 , 0.89030216, 0.56126291, 0.66594139, 0.64457743,
       0.95371133, 0.75124745, 0.53377201, 0.33719533, 0.24348715,
       0.23046879, 0.84179093, 0.68331511, 0.59509341, 0.16456724,
       0.94973819, 0.6760872 , 0.24586152, 0.29165011, 0.30082248])

In [67]:
eu = pd.cut(data, 4, precision=2) # 4 é a quantidade na lista - precision limita a precisão decimal em dois
eu

[(0.56, 0.76], (0.76, 0.95], (0.56, 0.76], (0.56, 0.76], (0.56, 0.76], ..., (0.76, 0.95], (0.56, 0.76], (0.16, 0.36], (0.16, 0.36], (0.16, 0.36]]
Length: 20
Categories (4, interval[float64]): [(0.16, 0.36] < (0.36, 0.56] < (0.56, 0.76] < (0.76, 0.95]]

In [68]:
eu.codes

array([2, 3, 2, 2, 2, 3, 2, 1, 0, 0, 0, 3, 2, 2, 0, 3, 2, 0, 0, 0],
      dtype=int8)

In [69]:
eu.categories

IntervalIndex([(0.16, 0.36], (0.36, 0.56], (0.56, 0.76], (0.76, 0.95]],
              closed='right',
              dtype='interval[float64]')

In [72]:
data = np.random.randn(1000)

In [73]:
cats = pd.qcut(data, 4) # separa em quantis

In [74]:
cats

[(0.0391, 0.688], (0.688, 3.005], (0.688, 3.005], (0.688, 3.005], (0.688, 3.005], ..., (-0.597, 0.0391], (-0.597, 0.0391], (0.688, 3.005], (0.0391, 0.688], (-2.997, -0.597]]
Length: 1000
Categories (4, interval[float64]): [(-2.997, -0.597] < (-0.597, 0.0391] < (0.0391, 0.688] < (0.688, 3.005]]

In [75]:
pd.value_counts(cats)

(-2.997, -0.597]    250
(-0.597, 0.0391]    250
(0.0391, 0.688]     250
(0.688, 3.005]      250
dtype: int64

In [77]:
# Detectando e filtrando valores discrepantes

In [78]:
# filtrar ou transforamr valores discrepantes (outliears) boa medida

In [114]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.head()

0         1         2         3
0  1.483701  0.785224  0.366769  1.232474
1 -1.191587 -0.918006  1.069292 -1.092549
2 -0.736309  0.230506 -0.786520 -0.800787
3  0.624277 -0.001140 -1.255224 -0.543949
4  1.535033 -0.503506  0.011733 -0.103335

In [115]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.010466     0.012845     0.063313    -0.018463
std       1.046467     1.015031     0.992608     0.998978
min      -3.630551    -3.097138    -3.053478    -3.187273
25%      -0.708967    -0.660826    -0.598896    -0.674596
50%       0.011053    -0.014310     0.037784    -0.011001
75%       0.669751     0.719514     0.707427     0.655272
max       3.836874     3.989588     3.218805     3.156967

In [116]:
col = data[2]

In [117]:
col[np.abs(col) > 3]

468    3.218805
518   -3.053478
Name: 2, dtype: float64

In [118]:
np.abs(data) # negativo fica positivo

0         1         2         3
0    1.483701  0.785224  0.366769  1.232474
1    1.191587  0.918006  1.069292  1.092549
2    0.736309  0.230506  0.786520  0.800787
3    0.624277  0.001140  1.255224  0.543949
4    1.535033  0.503506  0.011733  0.103335
..        ...       ...       ...       ...
995  0.128213  2.162633  0.077623  0.417128
996  0.212533  1.429249  0.506065  0.325363
997  1.535269  0.432098  1.190321  1.755394
998  0.020202  0.879108  0.886537  0.327708
999  0.766192  0.029471  0.365039  0.575274

[1000 rows x 4 columns]

In [120]:
np.sign(data)

0    1    2    3
0    1.0  1.0  1.0  1.0
1   -1.0 -1.0  1.0 -1.0
2   -1.0  1.0 -1.0 -1.0
3    1.0 -1.0 -1.0 -1.0
4    1.0 -1.0  1.0 -1.0
..   ...  ...  ...  ...
995  1.0 -1.0 -1.0  1.0
996  1.0 -1.0 -1.0  1.0
997 -1.0  1.0 -1.0  1.0
998  1.0  1.0 -1.0  1.0
999  1.0 -1.0 -1.0 -1.0

[1000 rows x 4 columns]

In [121]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
27   1.387915  0.516895 -0.068040 -3.109820
48   3.701881  1.299878  0.544193  0.434512
341 -2.090087 -0.493915 -0.386159 -3.187273
381  1.171557  3.989588 -0.238444  1.023029
387  3.125334 -0.243941 -0.036583 -0.705932
396 -0.245945  3.215629  0.647755  0.248314
421  0.638255  0.324986  0.313245  3.156967
446  3.836874 -0.340686 -0.906307  0.558456
468  0.879201  3.493451  3.218805  0.907881
518 -1.477935 -0.730204 -3.053478 -0.774762
547 -0.225137 -3.097138  0.554454 -0.491775
608 -3.630551 -1.171307 -1.068346  0.801989
882  3.804921 -0.655269 -0.377006  0.517735

In [122]:
data

0         1         2         3
0    1.483701  0.785224  0.366769  1.232474
1   -1.191587 -0.918006  1.069292 -1.092549
2   -0.736309  0.230506 -0.786520 -0.800787
3    0.624277 -0.001140 -1.255224 -0.543949
4    1.535033 -0.503506  0.011733 -0.103335
..        ...       ...       ...       ...
995  0.128213 -2.162633 -0.077623  0.417128
996  0.212533 -1.429249 -0.506065  0.325363
997 -1.535269  0.432098 -1.190321  1.755394
998  0.020202  0.879108 -0.886537  0.327708
999  0.766192 -0.029471 -0.365039 -0.575274

[1000 rows x 4 columns]

In [123]:
data[np.abs(data) > 3] = np.sign(data) * 3 
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.012305     0.011244     0.063148    -0.018323
std       1.036426     1.009089     0.991769     0.997579
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.708967    -0.660826    -0.598896    -0.674596
50%       0.011053    -0.014310     0.037784    -0.011001
75%       0.669751     0.719514     0.707427     0.655272
max       3.000000     3.000000     3.000000     3.000000

In [127]:
# np.sign() tudo que é valor vira 1

In [129]:
lista =[2, 3,41, 2,3 ,45]

In [130]:
np.sign(lista)

array([1, 1, 1, 1, 1, 1])

In [131]:
# np.abs() positivo vira negativo

In [2]:
# Permutação e amostragem aleatória

In [3]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [7]:
sampler = np.random.permutation(5)
sampler

array([1, 4, 2, 3, 0])

In [12]:
dados = [1, 2, 3, 6]
dados

[1, 2, 3, 6]

In [17]:
np.random.permutation(dados) # shift + enter vai modificando

array([2, 1, 6, 3])

In [18]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [19]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11
3  12  13  14  15
0   0   1   2   3

In [21]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11
3  12  13  14  15
0   0   1   2   3

In [28]:
df.sample(n=3) # pega amostragem de 3 linhas - shift + enter para mudar

0   1   2   3
3  12  13  14  15
4  16  17  18  19
2   8   9  10  11

In [29]:
choices = pd.Series([5, 7, -1, 6, 4])
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [33]:
draws = choices.sample(n=10, replace=True) # pega mais que o limite e pode repetir
draws

0    5
3    6
2   -1
4    4
1    7
3    6
4    4
1    7
4    4
1    7
dtype: int64

In [34]:
# Calculando variáveis indicadoras / dummy

In [35]:
# aprendizado de máquina (machine learning) consiste em conveter uma váriavel de categorais em uma matriz "dummy" ou "indicadora"

In [119]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                  'data1': [1, 2, 1, 14, 5, 6]})
df

key  data1
0   b      1
1   b      2
2   a      1
3   c     14
4   a      5
5   b      6

In [121]:
pd.get_dummies(df['key']) # adiciona 1 em todos os elementos que o df tem acima exemplo b 0, logo embaixo a coluna
# b e a linha 0 possui 1

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [39]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [7]:
mnames = ['movie_id', 'title', 'genres']
mnames

['movie_id', 'title', 'genres']

In [9]:
movies = pd.read_table('datasets/movielens/movies.dat', sep='::', header=None, names=mnames)
movies

<ipython-input-9-6a6b589583b4>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies = pd.read_table('datasets/movielens/movies.dat', sep='::', header=None, names=mnames)


movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres  
0      Animation|Children's|Comedy  
1     Adventure|Children's|Fantasy  
2                   Comedy|Romance  
3                     Comedy|Drama  
4                           Comedy  
...                            ...  
3878                        Comedy  
3879                         Drama  
3880                         Drama  
3881                         Drama  
3882                Drama|Thriller  

[3883 rows x 3 columns]

In [10]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [22]:
all_genres = []
for x in movies.genres:
    print(x)


Animation|Children's|Comedy
Adventure|Children's|Fantasy
Comedy|Romance
Comedy|Drama
Comedy
Action|Crime|Thriller
Comedy|Romance
Adventure|Children's
Action
Action|Adventure|Thriller
Comedy|Drama|Romance
Comedy|Horror
Animation|Children's
Drama
Action|Adventure|Romance
Drama|Thriller
Drama|Romance
Thriller
Comedy
Action
Action|Comedy|Drama
Crime|Drama|Thriller
Thriller
Drama|Sci-Fi
Drama|Romance
Drama
Drama
Romance
Adventure|Sci-Fi
Drama
Drama
Drama|Sci-Fi
Adventure|Romance
Children's|Comedy|Drama
Drama|Romance
Drama
Documentary
Comedy
Comedy|Romance
Drama
Drama|War
Action|Crime|Drama
Drama
Action|Adventure
Comedy|Drama
Drama|Romance
Crime|Thriller
Animation|Children's|Musical|Romance
Drama|Romance
Crime|Thriller
Action|Drama|Thriller
Comedy
Drama
Children's|Comedy
Drama
Adventure|Children's|Fantasy
Drama
Drama|Romance
Drama|Mystery
Adventure|Children's|Fantasy
Drama|Thriller
Drama
Comedy
Comedy|Romance
Comedy
Sci-Fi|Thriller
Drama
Comedy|Romance
Comedy
Action|Comedy|Crime|Horror|Thril

Crime|Thriller
Crime|Thriller
Comedy|Drama
Action|Comedy
Comedy
Comedy|Drama
Comedy|Drama
Drama
Drama
Drama
Comedy
Crime
Drama
Horror
Comedy|Romance
Drama|Musical
Comedy
Comedy|Drama
Documentary
Drama
Drama
Drama
Horror
Horror
Horror
Drama|Fantasy
Comedy
Comedy
Horror|Sci-Fi
Comedy
Comedy
Adventure|Sci-Fi
Adventure|Sci-Fi
Comedy|Horror
Comedy
Horror
Horror|Sci-Fi
Horror|Sci-Fi
Horror|Sci-Fi
Sci-Fi
Horror
Drama|Thriller
Sci-Fi|Thriller
Horror
Horror
Horror
Horror
Horror
Comedy
Comedy|Drama
Adventure|Animation|Children's
Action|Drama|Thriller
Thriller
Comedy
Drama
Drama
Drama
Drama|Thriller


In [24]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [25]:
all_genres


['Animation',
 "Children's",
 'Comedy',
 'Adventure',
 "Children's",
 'Fantasy',
 'Comedy',
 'Romance',
 'Comedy',
 'Drama',
 'Comedy',
 'Action',
 'Crime',
 'Thriller',
 'Comedy',
 'Romance',
 'Adventure',
 "Children's",
 'Action',
 'Action',
 'Adventure',
 'Thriller',
 'Comedy',
 'Drama',
 'Romance',
 'Comedy',
 'Horror',
 'Animation',
 "Children's",
 'Drama',
 'Action',
 'Adventure',
 'Romance',
 'Drama',
 'Thriller',
 'Drama',
 'Romance',
 'Thriller',
 'Comedy',
 'Action',
 'Action',
 'Comedy',
 'Drama',
 'Crime',
 'Drama',
 'Thriller',
 'Thriller',
 'Drama',
 'Sci-Fi',
 'Drama',
 'Romance',
 'Drama',
 'Drama',
 'Romance',
 'Adventure',
 'Sci-Fi',
 'Drama',
 'Drama',
 'Drama',
 'Sci-Fi',
 'Adventure',
 'Romance',
 "Children's",
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Drama',
 'Documentary',
 'Comedy',
 'Comedy',
 'Romance',
 'Drama',
 'Drama',
 'War',
 'Action',
 'Crime',
 'Drama',
 'Drama',
 'Action',
 'Adventure',
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Crime',
 'Thrill

In [33]:
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [34]:
# dataframe indicador

In [39]:
zero_matrix = np.zeros((len(movies)))
len(movies)

3883

In [40]:
len(zero_matrix)

3883

In [41]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [44]:
dummies = pd.DataFrame(zero_matrix, columns=genres)
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    0.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [46]:
gen = movies.genres[0]
gen

"Animation|Children's|Comedy"

In [47]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [48]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [51]:
dummies.columns

Index(['Animation', 'Children's', 'Comedy', 'Adventure', 'Fantasy', 'Romance',
       'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Sci-Fi',
       'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir', 'Western'],
      dtype='object')

In [52]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [59]:
for i, gen in enumerate(movies.genres):
    print(gen)

Animation|Children's|Comedy
Adventure|Children's|Fantasy
Comedy|Romance
Comedy|Drama
Comedy
Action|Crime|Thriller
Comedy|Romance
Adventure|Children's
Action
Action|Adventure|Thriller
Comedy|Drama|Romance
Comedy|Horror
Animation|Children's
Drama
Action|Adventure|Romance
Drama|Thriller
Drama|Romance
Thriller
Comedy
Action
Action|Comedy|Drama
Crime|Drama|Thriller
Thriller
Drama|Sci-Fi
Drama|Romance
Drama
Drama
Romance
Adventure|Sci-Fi
Drama
Drama
Drama|Sci-Fi
Adventure|Romance
Children's|Comedy|Drama
Drama|Romance
Drama
Documentary
Comedy
Comedy|Romance
Drama
Drama|War
Action|Crime|Drama
Drama
Action|Adventure
Comedy|Drama
Drama|Romance
Crime|Thriller
Animation|Children's|Musical|Romance
Drama|Romance
Crime|Thriller
Action|Drama|Thriller
Comedy
Drama
Children's|Comedy
Drama
Adventure|Children's|Fantasy
Drama
Drama|Romance
Drama|Mystery
Adventure|Children's|Fantasy
Drama|Thriller
Drama
Comedy
Comedy|Romance
Comedy
Sci-Fi|Thriller
Drama
Comedy|Romance
Comedy
Action|Comedy|Crime|Horror|Thril

In [60]:
movies.genres

0        Animation|Children's|Comedy
1       Adventure|Children's|Fantasy
2                     Comedy|Romance
3                       Comedy|Drama
4                             Comedy
                    ...             
3878                          Comedy
3879                           Drama
3880                           Drama
3881                           Drama
3882                  Drama|Thriller
Name: genres, Length: 3883, dtype: object

In [66]:
dummies.columns

Index(['Animation', 'Children's', 'Comedy', 'Adventure', 'Fantasy', 'Romance',
       'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Sci-Fi',
       'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir', 'Western'],
      dtype='object')

In [63]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|')) # get_indexer aplica a lista dummies.columns no gen.split() col in col index
    dummies.iloc[i, indices] = 1

[0 1 2]
[3 1 4]
[2 5]
[2 6]
[2]
[7 8 9]
[2 5]
[3 1]
[7]
[7 3 9]
[2 6 5]
[ 2 10]
[0 1]
[6]
[7 3 5]
[6 9]
[6 5]
[9]
[2]
[7]
[7 2 6]
[8 6 9]
[9]
[ 6 11]
[6 5]
[6]
[6]
[5]
[ 3 11]
[6]
[6]
[ 6 11]
[3 5]
[1 2 6]
[6 5]
[6]
[12]
[2]
[2 5]
[6]
[ 6 13]
[7 8 6]
[6]
[7 3]
[2 6]
[6 5]
[8 9]
[ 0  1 14  5]
[6 5]
[8 9]
[7 6 9]
[2]
[6]
[1 2]
[6]
[3 1 4]
[6]
[6 5]
[ 6 15]
[3 1 4]
[6 9]
[6]
[2]
[2 5]
[2]
[11  9]
[6]
[2 5]
[2]
[ 7  2  8 10  9]
[7]
[2 6]
[ 6 14]
[6 5]
[2 6]
[11  9]
[12]
[6]
[6 9]
[6]
[8 6 5]
[6]
[6]
[2 6]
[6 5]
[3 6]
[1 2]
[2]
[7 9]
[6]
[6 9]
[2 5]
[6]
[7 9]
[2]
[6]
[7 9]
[12]
[6 9]
[2]
[2]
[9]
[2]
[6 5]
[2 6]
[ 3  1  2 14]
[12]
[2]
[ 7  6 13]
[6 9]
[7 3 8]
[ 6 15]
[6]
[2]
[12]
[8]
[2 5]
[2]
[6]
[6]
[2 5]
[ 6 15  5]
[6]
[2]
[3 1 4]
[6]
[12]
[2 5]
[6]
[6 5]
[9]
[2 6]
[12]
[2]
[12]
[12]
[6]
[7 6]
[6 5]
[2]
[6]
[6]
[2]
[7]
[3 1]
[6]
[6]
[8 6 9]
[6]
[ 6  5 13]
[10]
[7 3 2 8]
[6]
[ 6 13]
[2]
[ 2 13]
[3 1]
[6]
[ 7  3 15 11]
[ 6  9 13]
[12]
[7 5 9]
[ 8 16 15  9]
[7 9]
[2 6]
[6]
[7 3 6 5]
[3 1 6]


[2]
[12]
[2 5]
[15]
[6]
[8 6]
[2 6]
[2 5]
[12]
[6]
[8 9]
[7 2 8 6]
[1 2]
[5]
[2 6]
[5]
[7 5 9]
[7 6 9]
[2 6]
[6 9]
[15]
[2]
[6]
[ 6 14]
[ 7  6  9 13]
[ 0  1 14]
[2]
[5]
[2]
[7 3 1]
[6 5]
[7]
[6 5]
[7 3 9]
[2 8]
[8]
[5]
[2]
[6]
[ 6 13]
[6]
[6]
[6]
[2]
[2]
[5]
[6 9]
[2]
[2]
[7 9]
[6]
[5]
[6]
[7 8 5]
[6]
[7 3 1 4]
[2]
[ 7 11]
[2]
[6]
[6]
[2]
[6]
[6]
[6 5]
[2]
[3 1]
[2 8]
[2 5]
[2 6 5]
[6]
[ 7  3 11  9]
[6]
[2]
[1 6]
[6]
[6 5]
[2 5]
[3 1 6]
[7 3 9]
[2]
[6 5]
[6]
[7 5 9]
[6]
[2]
[6]
[2]
[7 3 8]
[6]
[2 5]
[2 9]
[ 3  0  1  2 14]
[6]
[ 8  6 15]
[2 5]
[11]
[2 5]
[6]
[ 7 11  9]
[5]
[6]
[6]
[8]
[6]
[ 7  3  2 11]
[2]
[3 1]
[1 4]
[ 6 11]
[2]
[ 7  6 13]
[7 3]
[1 2]
[ 8  6 15]
[ 7 15 11  9]
[ 7  3 11  9]
[1 2]
[2 5]
[6]
[3 1 6]
[6]
[ 7 15  5  9]
[8 6 9]
[7]
[6 5]
[ 8  6 16]
[2]
[11  9]
[7 2]
[3 5]
[7 3]
[7 9]
[6]
[7 9]
[6]
[2]
[6]
[2]
[3 9]
[ 7  9 13]
[ 8 16 15  9]
[ 6 13]
[8 6 9]
[6]
[2 6]
[10]
[6]
[15  9]
[7 6 9]
[ 7  8 15]
[6]
[2 5]
[2 6]
[9]
[2 5]
[6]
[6]
[7 9]
[6 5]
[2]
[2]
[2 6]
[6 5]
[10 15  9

[2]
[ 6 15  5]
[0 1]
[ 6 14]
[10]
[7 3 2]
[7 3 2]
[7 9]
[6]
[2]
[2 5]
[6 5]
[1 2]
[6]
[2 5]
[2]
[ 6 13]
[2]
[7 6]
[7 6]
[6 5]
[3]
[17]
[ 2 13]
[10 15]
[3 0 1]
[10 11]
[10 11]
[10  9]
[10  9]
[6]
[7 3]
[6 5]
[2]
[6]
[12]
[6 5]
[6]
[7 8 6]
[2]
[2 6]
[2]
[ 7  3 11  9]
[8 9]
[2]
[6 5]
[6 5]
[17]
[17]
[2]
[7 2]
[6]
[2 6]
[6 5]
[6]
[6]
[12]
[6]
[6]
[6]
[14]
[2 5]
[2]
[2]
[6]
[6 9]
[16]
[14  5 13]
[6 5]
[6 5]
[ 7 13]
[15]
[ 2 14]
[7]
[7]
[7]
[3 6 5]
[ 7 17]
[8 9]
[1 2]
[6]
[6]
[7 8 9]
[6]
[6]
[6]
[6]
[2 6]
[2 5]
[8 6]
[6]
[7]
[6]
[6 9]
[ 3  4 11]
[6 5]
[3 6]
[14]
[ 6 13]
[2]
[10  9]
[6]
[ 6 10]
[2 6]
[2 5]
[6]
[6]
[12]
[10  9]
[9]
[12]
[ 7  8 11]
[ 7  8 11]
[ 3  0 16]
[6]
[7]
[7]
[7]
[10  9]
[7]
[6]
[10]
[6]
[2]
[5]
[2]
[7 3 0]
[6]
[12]
[2 6]
[2 5]
[9]
[6]
[12]
[9]
[6]
[6]
[6]
[2]
[ 2 10]
[2]
[9]
[10]
[10]
[10]
[8 6]
[7 6]
[10]
[2]
[2 5]
[10 11]
[17]
[10]
[10]
[2]
[7 6]
[ 2  6 17]
[2]
[11]
[ 2 11]
[0 1]
[ 2  6 13]
[3]
[ 2  6 17]
[6]
[2]
[2]
[2]
[2]
[2]
[15  5  9]
[2 6]
[2 5]
[6]
[2]
[ 2 13]
[

In [70]:
dummies.columns

Index(['Animation', 'Children's', 'Comedy', 'Adventure', 'Fantasy', 'Romance',
       'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Sci-Fi',
       'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir', 'Western'],
      dtype='object')

In [78]:
dummies.iloc[0, [0,1,2]]

Animation     1.0
Children's    1.0
Comedy        1.0
Name: 0, dtype: float64

In [79]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           1.0         1.0     1.0        0.0      0.0      0.0    0.0   
1           0.0         1.0     0.0        1.0      1.0      0.0    0.0   
2           0.0         0.0     1.0        0.0      0.0      1.0    0.0   
3           0.0         0.0     1.0        0.0      0.0      0.0    1.0   
4           0.0         0.0     1.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    1.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       1.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [84]:
movies

movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres  
0      Animation|Children's|Comedy  
1     Adventure|Children's|Fantasy  
2                   Comedy|Romance  
3                     Comedy|Drama  
4                           Comedy  
...                            ...  
3878                        Comedy  
3879                         Drama  
3880                         Drama  
3881                         Drama  
3882                Drama|Thriller  

[3883 rows x 3 columns]

In [82]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.head()

movie_id                               title                        genres  \
0         1                    Toy Story (1995)   Animation|Children's|Comedy   
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy   
2         3             Grumpier Old Men (1995)                Comedy|Romance   
3         4            Waiting to Exhale (1995)                  Comedy|Drama   
4         5  Father of the Bride Part II (1995)                        Comedy   

   Genre_Animation  Genre_Children's  Genre_Comedy  Genre_Adventure  \
0              1.0               1.0           1.0              0.0   
1              0.0               1.0           0.0              1.0   
2              0.0               0.0           1.0              0.0   
3              0.0               0.0           1.0              0.0   
4              0.0               0.0           1.0              0.0   

   Genre_Fantasy  Genre_Romance  Genre_Drama  ...  Genre_Crime  \
0            0.0            0.0          0.0  ...          0.0   
1            1.0            0.0          0.0  ...          0.0   
2            0.0            1.0          0.0  ...          0.0   
3            0.0            0.0          1.0  ...          0.0   
4            0.0            0.0          0.0  ...          0.0   

   Genre_Thriller  Genre_Horror  Genre_Sci-Fi  Genre_Documentary  Genre_War  \
0             0.0           0.0           0.0                0.0        0.0   
1             0.0           0.0           0.0                0.0        0.0   
2             0.0           0.0           0.0                0.0        0.0   
3             0.0           0.0           0.0                0.0        0.0   
4             0.0           0.0           0.0                0.0        0.0   

   Genre_Musical  Genre_Mystery  Genre_Film-Noir  Genre_Western  
0            0.0            0.0              0.0            0.0  
1            0.0            0.0              0.0            0.0  
2            0.0            0.0              0.0            0.0  
3            0.0            0.0              0.0            0.0  
4            0.0            0.0              0.0            0.0  

[5 rows x 21 columns]

In [83]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                              1.0
Genre_Children's                             1.0
Genre_Comedy                                 1.0
Genre_Adventure                              0.0
Genre_Fantasy                                0.0
Genre_Romance                                0.0
Genre_Drama                                  0.0
Genre_Action                                 0.0
Genre_Crime                                  0.0
Genre_Thriller                               0.0
Genre_Horror                                 0.0
Genre_Sci-Fi                                 0.0
Genre_Documentary                            0.0
Genre_War                                    0.0
Genre_Musical                                0.0
Genre_Mystery                                0.0
Genre_Film-Noir                              0.0
Genre_Western       

In [85]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [88]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [118]:
# Manipulação de String

In [125]:
# Métodos de objetos string

In [126]:
val = 'a, b, guido'

In [127]:
val.split(',')

['a', ' b', ' guido']

In [128]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [129]:
first, second, third = pieces

In [131]:
first + '::' + second + '::' + third

'a::b::guido'

In [132]:
'::'.join(pieces) # defaz a lista e no lugar de , colocar ::

'a::b::guido'

In [133]:
'guido' in val

True

In [134]:
val.index(',')

1

In [136]:
val.find(':') # diferença de index

-1

In [138]:
val

'a, b, guido'

In [140]:
val.index('b')

3

In [141]:
val.count(',')

2

In [142]:
val.replace(',', '::')

'a:: b:: guido'

In [143]:
val.replace(',', '')

'a b guido'

In [146]:
# Expressões regulares para filtrar

In [147]:
# regex

In [148]:
# modulo re se enqundra em três categorias: correspondência, substituição e separação de padrões

In [150]:
import re #regex

In [151]:
text = "foo    bar\t baz  \tqux"

In [152]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [156]:
regex = re.compile('\s+') # instancia um objeto regex bom por conta que economiza ciclos de CPU
regex

re.compile(r'\s+', re.UNICODE)

In [157]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [159]:
regex.findall(text) # padrões que correspondem à regex

['    ', '\t ', '  \t']

In [195]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [161]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [162]:
pattern

'[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}'

In [163]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [164]:
regex

re.compile(r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}', re.IGNORECASE|re.UNICODE)

In [166]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [167]:
m = regex.search(text)

In [168]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [169]:
m.start()

5

In [170]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [201]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [202]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [203]:
m = regex.match("wesm@bright.net")

In [205]:
m.groups()

('wesm', 'bright', 'net')

In [206]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [208]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



In [209]:
# Funções de string vetorizadas no pandas

In [210]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
       'Rob': 'rob@gmail.com', 'Wes': np.nan}
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [211]:
data = pd.Series(data)

In [212]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [213]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [215]:
data.str.contains('gmail') # verifica se tem gmail

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [216]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [218]:
data.str.findall(pattern)

Dave      []
Steve     []
Rob       []
Wes      NaN
dtype: object

In [219]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [220]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [221]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object